### ISSUE TITLE
Enderman attack

### ISSUE THREAD

**Issue by Squaredude** [Judge40/BetterMobGriefingGameRule#20]
MC version: 1.12.2
Mod: 7.0.1
Forge: 14.23.3.2695

Settings: mobGriefing = false - mobGriefing villager = true - mobGriefing sheep = true

Endermen don't pick up items, but they seem to be able to destroy their surroundings when attacking me. Say, if I'm holed up in a small place, they try to destroy things to get to me.

For reference, Creepers exploding behave as expected. Their explosions don't damage their surroundings.

Edit: Just saw it happen a lot more clearly now. The Endermen are able to hit things with their arms. This knocks blocks off, or breaks them completely (glass).

**Comment by Judge40** [comment]
I'm not able to reproduce this either with or without my mod installed, also looking at the code I can't see anything to suggest that this behaviour is possible.

Are you using any other mods which could be changing the Enderman behaviour?

**Comment by Squaredude** [comment]
Yep. I feel silly now. I did the typical disabling of other mods one by one, and found out there's a feature in Quark that's called "Enderman Anti-Cheese" which specifically has Endermen doing this.

Disabling the feature has everything working as expected. I apologize for any wasted time.

**Comment by Judge40** [comment]
No need to apologise, I'm just happy it's resolved.
Thanks for taking the time to verify.
